"Keybindings
inoremap jj <ESC>
let mapleader = "\<Space>"
filetype plugin indent on
vnoremap . :norm.<CR>
map <C-n> :NERDTreeToggle<CR>

set background=dark
set whichwrap=b,s,<,>,[,]

set history=500
set encoding=utf-8
set relativenumber
set number
set ignorecase
filetype off

set autoindent
set copyindent
" set undofile "undo file

" show ruler
set ruler

" case-insensetive search
set ignorecase
set smartcase
" hl while typing search
set incsearch
" hl after executing search or :/\v ...:
" set hlsearch

" enable syntax hl
syntax enable
set nocompatible "show incomplete command

" packages
packadd! matchit

" lines before and after cursor
set scrolloff=3

set showcmd
set showmode
set showmatch

"delete over linebreack
set backspace=indent,eol,start

set nowrap
set list
set lcs=tab:>-,eol:<,nbsp:%

"disable arrowkeys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

"Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-surround' "add surround
Plugin 'tpope/vim-repeat' "add repeat action to vim-surround
Plugin 'scrooloose/nerdtree' "Filebrowser
call vundle#end()
" My Bundles here:
" 
" original repos on github
" Bundle 'tpope/vim-fugitive'
" Bundle 'Lokaltog/vim-easymotion'
" Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
" Bundle 'tpope/vim-rails.git'
" vim-scripts repos
" Bundle 'L9'
" Bundle 'FuzzyFinder'
" non github repos
" Bundle 'git://git.wincent.com/command-t.git'
" ...
"
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..
"
