"Keybindings

inoremap jj <ESC>
let mapleader = "\<Space>"
filetype plugin indent on
vnoremap . :norm.<CR>
map <C-n> :NERDTreeToggle<CR>

set background=dark
set whichwrap=b,s,<,>,[,] "Backspace over Linebreak


" hl after executing search or :/\v ...:
" set hlsearch

" packages
"packadd! matchit

syntax enable

"case-insensetive search
set ignorecase

"addition to igorecase
set smartcase

"show incomplete command
set nocompatible

"hl while typing search
set incsearch

"show ruler
set ruler

"lines before and after cursor
set scrolloff=3

"show command while typing
set showcmd

"show Insert,Visual.. modes
set showmode

"show cursorline
set cursorline

"show mathcing brackets/parents
set showmatch

"delete over linebreack
set backspace=indent,eol,start

"visual tab,eol
set lcs=tab:>-,eol:<,nbsp:%

"keep indent after linebreak
set autoindent

"keep indent while copying
set copyindent

"remember command lines
set history=500

"set encoding
set encoding=utf-8


set relativenumber
set number


" set undofile "undo file

set nowrap
set list

"disable arrowkeys in Insert-Mode
"map <up> <nop>
"map <down> <nop>
"map <left> <nop>
"map <right> <nop>

"Vundle
filetype off 
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-surround' "add surround
Plugin 'tpope/vim-repeat' "add repeat action to vim-surround
Plugin 'scrooloose/nerdtree' "Filebrowser
call vundle#end()
" My Bundles here:
" 
" original repos on github
" Bundle 'tpope/vim-fugitive'
" Bundle 'Lokaltog/vim-easymotion'
" Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
" Bundle 'tpope/vim-rails.git'
" vim-scripts repos
" Bundle 'L9'
" Bundle 'FuzzyFinder'
" non github repos
" Bundle 'git://git.wincent.com/command-t.git'
" ...
"
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..
"
