inoremap jj <ESC>
let mapleader = "\<Space>"
filetype plugin indent on
vnoremap . :norm.<CR>
set background=dark
set whichwrap=b,s,<,>,[,]

set history=500
set encoding=utf-8
set relativenumber
set number
set ignorecase
set filetype=unix

set autoindent
set copyindent
set undofile

" show ruler
set ruler

" case-insensetive search
set ignorecase
set smartcase
" hl while typing search
set incsearch
" hl after executing search or :/\v ...:
" set hlsearch

" enable syntax hl
syntax enable
set nocompatible "show incomplete command

" packages
packadd! matchit

" lines before and after cursor
set scrolloff=3

set showcmd
set showmode
set showmatch

"delete over linebreack
set backspace=indent,eol,start

set nowrap
set list
set lcs=tab:>-,eol:<,nbsp:%

"disable arrowkeys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

